### ISSUE TITLE
Panel is going out of the window

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel#72] opened 2017-10-01 18:57 UTC
![screenshot_2017-10-01_14-56-56](https://user-images.githubusercontent.com/5307016/31057919-cb947c30-a6b8-11e7-9937-c4c9697186a2.png)

**Comment by rilian-la-te** [comment] 2017-10-01 20:00
Panel version and config file, please.

**Comment by rilian-la-te** [comment] 2017-10-02 05:39
Duplicate of #70

**Closed by rilian-la-te** 2017-10-02 05:39 UTC
